### ISSUE TITLE
User can see open issues

### ISSUE THREAD

**Issue by bwencke** [xternprojects/cultural-trail-iOS#7]
It needs to be easy to switch between list and map view
- [x] #8  - List of issues
- [ ] #9  - Map of issues
- [x] #10 - Issue Details
- [ ] #11 - Pictures, GPS, description, etc.
